config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the sdfasfDSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:show] do
    resources :bookings, only: [:index]
  end

  # above code is me trying to refactor the below line
  # get "/users/:id", to: "users#show", as: :user

  resources :reptiles do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :reptile
  validates :start_date, presence: true
  validates :end_date, presence: true

  # validate :start_date_cannot_be_in_the_past
  # validate :end_date_after_start_date

  # private

  # def start_date_cannot_be_in_the_past
  #   errors.add(:start_date, "can't be in the past") if start_date.present? && start_date < Date.today
  # end

  # def end_date_after_start_date
  #   return if end_date.blank? || start_date.blank?

  #   errors.add(:end_date, "must be after the start date") if end_date < start_date
  # end
end

app/models/reptile.rb
class Reptile < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :description, presence: true
  validates :species, presence: true
  validates :daily_price, presence: true, numericality: true

  has_one_attached :photo

#   private

#   def price_format
#     unless read_attribute_before_type_cast('price') =~ PRICE_REGEXP
#       errors.add('price', 'must match the correct format')
#     end
# end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reptiles
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
    @user = current_user
  end

  def new
    @reptile = Reptile.find(params[:reptile_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.reptile = Reptile.find(params[:reptile_id])
    @booking.user = current_user
    if @booking.save
      redirect_to user_bookings_path(@booking.user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_bookings_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :reptile_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reptiles_controller.rb
class ReptilesController < ApplicationController
  def index
    @reptiles = Reptile.all
  end

  def new
    @reptile = Reptile.new
  end

  def show
    @reptile = Reptile.find(params[:id])
  end

  def create
    @reptile = Reptile.new(reptile_params)
    @reptile.user = current_user
    if @reptile.save
      redirect_to reptiles_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @reptile = Reptile.find(params[:id])
    @reptile.destroy
    redirect_to reptiles_path
  end

  private

  def reptile_params
    params.require(:reptile).permit(:name, :description, :species, :daily_price, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container container-mb" id="text-decoration-none">

  <div class="row">

    <div class="col-8">
      <div class="bookings-main-card">
        <h1 class="title">Upcoming bookings</h1>
        <% @user.bookings.each do |booking| %>
            <% if booking.end_date >= Date.today %>
              <div class="border-bottom my-5">
                <div>
                  <%= link_to reptile_path(booking.reptile) do %>
                    <div class="bookings-individual-card">
                      <div class="d-flex justify-content-between">
                        <h4><strong><%= "#{booking.reptile.name} the #{booking.reptile.species}" %></strong></h4>
                        <div>
                          <p><%= "#{booking.start_date} to #{booking.end_date}" %></p>
                        </div>
                      </div>
                      <% booking_length = booking.end_date - booking.start_date + 1 %>
                      <% booking_price = booking_length * (booking.reptile.daily_price) %>
                      <%= "£#{booking_price} (#{booking_length} days @ £#{booking.reptile.daily_price}/day)" %>
                    </div>

                    <div class="d-flex justify-content-end">
                      <div class="m-3">
                        <%= link_to "Delete Booking", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?" }, class: "bttn-small", style: "--color: #3d673e;"  %>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
        <% end %>
      </div>
    </div>

    <div class="col-4">
      <div class="bookings-main-card">
        <h3 class="title">Past bookings</h3>
        <% @user.bookings.each do |booking| %>
        <%= link_to reptile_path(booking.reptile) do %>
            <% if booking.end_date < Date.today %>
<div class="border-bottom my-5">
                <div>
                  <%= link_to reptile_path(booking.reptile) do %>
                    <div class="bookings-individual-card">
                      <div class="d-flex justify-content-between">
                        <h6><strong><%= "#{booking.reptile.name} the #{booking.reptile.species}" %></strong></h6>
                        <div>
                          <h6><%= "#{booking.start_date} to #{booking.end_date}" %></h6>
                        </div>
                      </div>
                      <% booking_length = booking.end_date - booking.start_date + 1 %>
                      <% booking_price = booking_length * (booking.reptile.daily_price) %>
                      <h6><%= "£#{booking_price} (#{booking_length} days @ £#{booking.reptile.daily_price}/day)" %></h6>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>

</div>

app/views/bookings/new.html.erb
<div class="container">

  <div class="row">

    <div class="col-6">
      <h1 class="green-title">Book <%= @reptile.name %></h1>


      <%= simple_form_for [@reptile, @booking] do |f| %>
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true %>
        <%= f.submit class: 'bttn', value: "book"%>
      <% end %>

    </div>

    <div class="col-6">

      <% if @reptile.photo.attached? %>
        <%= cl_image_tag @reptile.photo.key,class: "reptile_image", height:500, width:600 %>
      <% end %>

    </div>

  </div>
    <div class="my-3">
          <%= link_to(reptiles_path, class: "bttn", style: "--color: #3d673e;") do %>
          back to reptiles
          <% end %>
      </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

   <title> Rent-A-Reptile </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no", charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%# had to add "/assets/" to the above to make it work %>
    <%# ^ https://stackoverflow.com/questions/72448485/the-asset-application-js-is-not-present-in-the-asset-pipeline-in-rails-7 %>
  </head>

  <body>

    <%= render "shared/navbar" %>





    <p class="notice mb-0"><%= notice %></p>
     <p class="alert mb-0"><%= alert %></p>
    <%= yield %>

    <div class="footer">
      <div id="email" style ="font-family: Nunito, Helvetica, sans-serif;">
        <p> <i class="fa-regular fa-envelope"></i> rent-a-reptile@gmail.com </p>
      </div>
    <div id="number" style ="font-family: Nunito, Helvetica, sans-serif;">
        <p><i class="fa-solid fa-phone"></i> 01234 567890</p>

      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
    <%= image_tag "reptile.gif", class:"image" %>

app/views/reptiles/index.html.erb
<div class="container container-mb">
  <div class="cards">
    <% @reptiles.each do |reptile| %>
      <%= link_to reptile_path(reptile) do  %>
        <% if reptile.photo.attached? %>
          <div class="reusable-card" style=" background: url('  <%= cl_image_path reptile.photo.key%>');background-repeat: no-repeat;background-position: center;background-size: cover;">

            <div class="container__profile">
              <div class="container__profile__text">
                <div class="d-flex justify-content-between">
                  <h2><%= reptile.name %></h2>
                  <h2>£<%= reptile.daily_price %></h2>
                </div>
                <p><b><%= reptile.species %></b></p>
              </div>
            </div>
          </div>
      <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/reptiles/new.html.erb
<div class="m-5">
  <div class="container">


    <h1 class="green-title">List your reptilian friend</h1>

      <div class="row">

        <div class="col-6">
          <%= simple_form_for(@reptile) do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :species %>
          <%= f.input :daily_price %>
        </div>

        <div class="col-6">
          <%= f.input :photo, as: :file  %>
          </div>
          <%= f.submit class: 'bttn', value: "book", style: "--color: #3d673e;"%>
          <% end %>
        </div>

        <div class="button-right mt-3">
          <%= link_to(reptiles_path, class: "bttn") do %>
            back
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/reptiles/show.html.erb
 <div class="container-full-page">
      <div class="card-product align-items-flex-start" id="show-card">
        <% if @reptile.photo.attached? %>
        <%= cl_image_tag @reptile.photo.key,class: "reptile_image" %>
        <% end %>


            <div>
                  <div class="card-product-infos m-3 mb-5 pb-4" id="info">
                    <h3 class="info text-start">  Say hi to <%= @reptile.name%> <i class="fa-regular fa-handshake"></i></h3>
                    <div class= "text p-3">
                        <h2> <%= @reptile.species %></h2>
                        <p><%=@reptile.description%></p>
                       <strong> <h6 class= "m-2">£<%= @reptile.daily_price %> <h6> </strong>
                    </div>
                  </div>


                  <div class="d-flex justify-content-around mt-5">

                        <div class="m-5">
                          <%= link_to(new_reptile_booking_path(@reptile), class: "bttn", id: "book_button" ,style: "--color: darkseagreen;") do %>
                            <span></span>
                            <span></span>
                            <span></span>
                            <span></span>
                            book
                          <% end %>
                        </div>

                          <div class="d-flex align-items-center">
                            <div class="m-3">
                                <%= link_to(reptiles_path, class: "bttn", style: "--color: #3d673e;", id: "sideman_button") do %>
                                back
                                <% end %>
                            </div>


                              <%# if reptile.user= current_user %>
                            <div class="m-3">
                            <%= link_to "Delete", reptile_path(@reptile), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this reptile?" }, class: "bttn", style: "--color: #3d673e;" , id: "sideman_button" %>
                            </div>
                          </div>
                  </div>


              </div>





      </div>
</div>

app/views/shared/_complex_button.html.erb
 
<div class="m-3">
    <%= link_to(INPUT_path, class: "bttn", style: "--color: #3d673e;") do %>
    <span></span>
    <span></span>
    <span></span>
    <span></span> 
    INPUT
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div id="navbar"class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <div class="navbar-brand">
          <%= image_tag "logo.png" %>
      </div>
      <div class="nav-item active m-4">
        <marquee direction="left"><h1 style="font-stretch:expanded;"> Rent-A-Reptile</h1></marquee>
      </div>
    </div>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
                  <div class=" m-3">
                      <%= link_to(reptiles_path, class: "bttn", style: "--color: #3d673e;") do %>
                        See Reptiles
                        <% end %>
                    </div>
                    <div class=" m-3">
                      <%= link_to(new_reptile_path, class: "bttn", style: "--color: #3d673e;") do %>
                        List your Reptile
                        <% end %>
                    </div>
          <% else %>
            <li class="nav-item bttn">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>

        <div class="nav-item dropdown">
          <% if user_signed_in? %>
          <%= image_tag "dropdown_img.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Home", root_path, class: "dropdown-item" %>
              <%= link_to "Bookings", user_bookings_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          <% end %>
        </div>
      </div>



  </div>
</div>

app/views/users/show.html.erb
<div class="container">
This is a user's profile page

Include a link to bookings page
</div>